Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/PerceivedComplexity:
  Description: >-
                 A complexity metric geared towards measuring complexity for a
                 human reader.
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: >-
                 A complexity metric that is strongly correlated to the number
                 of test cases needed to validate a method.
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  Enabled: false

Metrics/AbcSize:
  Description: >-
                 A calculated magnitude based on number of assignments,
                 branches, and conditions.
  Enabled: false

Style/PredicateName:
  # Predicate name prefices.
  NamePrefix:
    - is_
    - has_
    - have_
  # Predicate name prefices that should be removed.
  NamePrefixBlacklist:
    - is_
    - has_
    - have_
  Enabled: false
